const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            fontFamily: {
                sans: ['Fredoka', 'Inter', ...defaultTheme.fontFamily.sans],
                fredoka: ['Fredoka', ...defaultTheme.fontFamily.sans],
                inter: ['Inter', ...defaultTheme.fontFamily.sans],
                quicksand: ['Quicksand', ...defaultTheme.fontFamily.sans],
                outfit: ['Outfit', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                // Kokokah Brand Colors
                primary: {
                    50: '#f0f7f8',
                    100: '#e0eff1',
                    200: '#c1dfe3',
                    300: '#a2cfd5',
                    400: '#63afb9',
                    500: '#2B6870',
                    600: '#004A53',
                    700: '#003d46',
                    800: '#003039',
                    900: '#00232c',
                },
                secondary: {
                    50: '#fffbf0',
                    100: '#fff7e0',
                    200: '#ffefcc',
                    300: '#ffe7b3',
                    400: '#ffdf99',
                    500: '#FDAF22',
                    600: '#fdbc47',
                    700: '#f5a500',
                    800: '#cc8400',
                    900: '#996300',
                },
                accent: {
                    light: '#FDBC47',
                    dark: '#004A53',
                    orange: '#FF6B35',
                    pink: '#FF1493',
                    green: '#4CAF50',
                },
                // Semantic Colors
                success: '#28a745',
                warning: '#ffc107',
                danger: '#dc3545',
                info: '#17a2b8',
                light: '#f8f9fa',
                dark: '#343a40',
                // Neutral Colors
                neutral: {
                    50: '#FFFFFF',
                    100: '#F6F8FA',
                    200: '#E9ECEF',
                    300: '#DEE2E6',
                    400: '#CED4DA',
                    500: '#ADB5BD',
                    600: '#6b737a',
                    700: '#495057',
                    800: '#343A40',
                    900: '#1C1D1D',
                },
            },
            spacing: {
                '128': '32rem',
                '144': '36rem',
                'xs': '4px',
                'sm': '8px',
                'md': '16px',
                'lg': '24px',
                'xl': '32px',
                '2xl': '40px',
                '3xl': '60px',
                '4xl': '80px',
            },
            borderRadius: {
                'xs': '4px',
                'sm': '6px',
                'md': '8px',
                'lg': '12px',
                'xl': '1rem',
                '2xl': '1.5rem',
                '3xl': '20px',
            },
            boxShadow: {
                'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                'md': '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
                'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
                'card': '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1rem' }],
                'sm': ['0.875rem', { lineHeight: '1.25rem' }],
                'base': ['1rem', { lineHeight: '1.5rem' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem' }],
                'xl': ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
                '5xl': ['3rem', { lineHeight: '1' }],
                // Kokokah Typography Scale
                'h1': ['56px', { lineHeight: '1.2', fontWeight: '700' }],
                'h2': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
                'h3': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
                'h4': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
                'h5': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
                'h6': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
                'body': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'small': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
            },
            transitionDuration: {
                '150': '150ms',
                '200': '200ms',
                '300': '300ms',
                '500': '500ms',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
    ],
};

